cluster: ""

traefik:
  fullnameOverride: traefik
  image:
    name: traefik
    tag: 2.4.8
  deployment:
    annotations:
      reloader.stakater.com/match: "true"
  globalArguments:
    - "--global.checknewversion"
    - "--serverstransport.insecureskipverify=true"
  logs:
    general:
      format: json
      level: INFO
    access:
      enabled: true
      format: json
  service:
    spec:
      externalTrafficPolicy: Local
  ports:
    web:
      redirectTo: websecure
    websecure:
      tls:
        enabled: true
  ingressRoute:
    dashboard:
      enabled: false
  pilot:
    enabled: true
  experimental:
    plugins:
      enabled: true
  rollingUpdate:
    maxUnavailable: 3
    maxSurge: 3
  resources:
    requests:
      cpu: "100m"
      memory: "50Mi"
    limits:
      cpu: "300m"
      memory: "150Mi"
  autoscaling:
    enabled: false
    minReplicas: 3
    maxReplicas: 30
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - traefik
            topologyKey: kubernetes.io/hostname

