{{- if .Values.storage.zfs.enabled -}}
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: argo-storage-class-zfs
parameters:
  fstype: zfs
  poolname: {{ .Values.storage.zfs.pool }}/{{ .Values.storage.zfs.dataset }}
  shared: "yes"
provisioner: zfs.csi.openebs.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
{{- end -}}